import "regenerator-runtime";
import "../scss/styles.scss";
import "./modal";
import "./infiniteScroll";
import "./infiniteScrollMyPage";
import './detectWord';
import "./activeNav";
import "./preventClick";
import "./selectedLanguage";